# Depth2Elevation - GAMUS Dataset Configuration

# 基本设置
model_name: "im2height"
# model_variant: "gradient_adaptive"
experiment_name: "im2height_gamus_vitb_50ep"
seed: 42
device: "cuda"

# 数据设置
data_root: 'D:/Height/test_data/'
dataset_name: "GAMUS"
input_size: 448
patch_size: 14
batch_size: 1
num_workers: 1

# 训练设置
num_epochs: 50
learning_rate: 5.0e-6
weight_decay: 0.01
optimizer: "adamw"
scheduler: "constant"

# 验证和保存
val_interval: 5
save_interval: 10
max_keep_ckpts: 3

# 路径设置
checkpoint_dir: "./checkpoints"
log_dir: "./logs"
result_dir: "./experiments"

# 模型配置
model_config:
  input_channels: 3



# 损失函数配置
loss_config:
  type: "l1"
  epsilon: 0.01

# 训练器配置
trainer_type: "depth"
use_multi_scale_output: false
compute_metrics_interval: 1
# log_scale_losses: true

# 数据增强配置
augmentation_config:
  horizontal_flip: 0.5
  color_jitter: 0.5
  gaussian_blur: 0.0